print("........................................")
print("TUGAS 1 SISTEM OPERASI KELAS A")
print("........................................")
print("Nama: Elfira Ratna Syaharani")
print("NPM: 21083010056")
print("........................................")
print("NOTE: ")
print("........................................")
print("Halo Dunia! \nIni adalah skrip Bash pertamaku di Linux! \n") 
